### PR TITLE
Refactoring templates to be similar to other sample apps

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
@bparees @rhcarvalho PTAL

**Comment by ewolinetz** [comment]
@bparees @rhcarvalho PTAL.  It looks like we grabbed the IST output already from PR #2

**Comment by bparees** [comment]
@ewolinetz the jury is stil out on whether we want to redeploy the DB on image change, since redeploying a DB when it's not backed by an NFS volume means you lose your db data.

**Comment by ewolinetz** [comment]
@bparees alright, I'll revert that portion for now and we can address that at a later time.

**Pull request merged**
