### PR TITLE
Fix compatibility with UBI 8 Perl images

### LINKED ISSUE #78: Incompatible with ubi8 perl images
Two issues occur attempting to use the dancer template with perl:5.26-el8:

1.  Only the very latest version of DBD::mysql will build with libmariadb client:  https://github.com/multi-arch/dancer-ex/commit/f3bb206873bf363cdfb90e60a64b3e7ef5162c6c

2. While RHSCL (RHEL 7) perl images included mod_perl, UBI 8 perl images use fcgi.  The build completes, but deploying the pod fails:
```
AH00526: Syntax error on line 3 of /opt/app-root/etc/httpd.d/dancer.conf:
Invalid command 'PerlResponseHandler', perhaps misspelled or defined by a module not included in the server configuration
```
Somehow, cfg/dancer.conf needs to be made compatible with fcgi as well, without breaking compatibility with mod_perl when built with RHEL7/RHSCL perl.

These issues now block https://github.com/openshift/cluster-samples-operator/pull/320

cc: @hhorak

### PR DESCRIPTION
**Pull request by yselkowitz**
Closes: https://github.com/sclorg/dancer-ex/issues/78

CC: @ppisar

### CODE REVIEW

**Comment by ppisar** [comment]
It looks good.

**Comment by yselkowitz** [comment]
Glad to hear it, now what?

**Comment by ppisar** [comment]
An owner of this repository should merge this pull request. The last merge commit
was by hhorak. So I think he's the owner.

**Comment by yselkowitz** [comment]
@pkubatrh is this something you could review in Honza's absence?

**Comment by pkubatrh** [comment]
Sure! Merging, thanks

**Comment by hhorak** [comment]
Thanks a lot folks!!!

**Pull request merged**
