### PR TITLE
Adding BuildConfig postCommit hook to run tests

### LINKED ISSUE #29: Add post build hook
Add an example build hook to run unit tests as part of the build.

:thought_balloon: I tried doing so myself but couldn't get it working without friction, so deferring it for later or someone else.

The hook shall be added to the BuildConfigs of our templates:

``` diff
+        "postCommit": {
+          "script": "perl -Iextlib/lib/perl5 t/*"
+        }
```

I am not sure about the right one-liner to run unit tests.

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes #29

### CODE REVIEW

**Comment by coreydaley** [comment]
@rhcarvalho @bparees Please review

**Comment by bparees** [comment]
@coreydaley how long do the tests take to run?

**Comment by coreydaley** [comment]
@bparees a few seconds

**Comment by bparees** [comment]
lgtm

**Pull request merged**
