### PR TITLE
Add liveness and readiness probe

### PR DESCRIPTION
**Pull request by mfojtik**
@bparees I believe this is the last one... same as PHP, i'm not creating special health check file here, but will ask @nhr to do one maybe ;-)

### CODE REVIEW

**Comment by bparees** [comment]
same question then...this will pass even if the DB isn't accessible?

**Comment by mfojtik** [comment]
@bparees not thanks to @nhr :-)

**Comment by mfojtik** [comment]
(do not merge this yet)

**Comment by mfojtik** [comment]
@bparees fixed, now it is checking db connection.

**Pull request merged**
