### PR TITLE
Standardize templates across examples

### PR DESCRIPTION
**Pull request by rhcarvalho**
@ewolinetz @bparees PTAL

note:
- the route will be changed in a follow-up PR for all framework examples

### CODE REVIEW

**Comment by ewolinetz** [comment]
@rhcarvalho a lot of these changes are already contained in PR #1. can check the differences between this PR and that one?

**Comment by rhcarvalho** [comment]
@ewolinetz sorry I didn't see that before :(
Unfortunately I don't have time to compare then right now, gotta catch a train...

**Comment by rhcarvalho** [comment]
@ewolinetz the diff:

```
diff --git a/openshift/templates/dancer-mysql.json b/openshift/templates/dancer-mysql.json
index 7153e4d..4f78928 100644
--- a/openshift/templates/dancer-mysql.json
+++ b/openshift/templates/dancer-mysql.json
@@ -50,16 +50,29 @@
       }
     },
     {
-      "kind": "ImageStream",
+      "kind": "ImageStreamTag",
       "apiVersion": "v1",
       "metadata": {
-        "name": "dancer-example",
+        "name": "dancer-example:latest",
         "annotations": {
           "description": "Keeps track of changes in the application image"
         }
       }
     },
     {
+      "kind": "ImageStreamTag",
+      "apiVersion": "v1",
+      "metadata": {
+        "name": "perl:5.16",
+        "annotations": {
+          "description": "Keeps track of changes in the Perl base image"
+        }
+      },
+      "spec": {
+        "dockerImageRepository": "openshift/perl-516-centos7"
+      }
+    },
+    {
       "kind": "BuildConfig",
       "apiVersion": "v1",
       "metadata": {
@@ -81,15 +94,14 @@
           "sourceStrategy": {
             "from": {
               "kind": "ImageStreamTag",
-              "namespace": "openshift",
               "name": "perl:5.16"
             }
           }
         },
         "output": {
           "to": {
-            "kind": "ImageStreamTag",
-            "name": "dancer-example:latest"
+            "kind": "ImageStream",
+            "name": "dancer-example"
           }
         },
         "triggers": [
@@ -99,7 +111,7 @@
           {
             "type": "GitHub",
             "github": {
-              "secret": "${GITHUB_WEBHOOK_SECRET}"
+              "secret": "secret123"
             }
           }
         ]
@@ -115,20 +127,6 @@
         }
       },
       "spec": {
-        "strategy": {
-          "type": "Recreate",
-          "recreateParams": {
-            "post": {
-              "failurePolicy": "Abort",
-              "execNewPod": {
-                "command": [
-                  "./run.sh"
-                ],
-                "containerName": "dancer-example"
-              }
-            }
-          }
-        },
         "triggers": [
           {
             "type": "ImageChange",
@@ -229,6 +227,20 @@
         },
         "triggers": [
           {
+            "type": "ImageChange",
+            "imageChangeParams": {
+              "automatic": true,
+              "containerNames": [
+                "mysql"
+              ],
+              "from": {
+                "kind": "ImageStreamTag",
+                "name": "mysql:5.5"
+              },
+              "lastTriggeredImage": ""
+            }
+          },
+          {
             "type": "ConfigChange"
           }
         ],
@@ -286,14 +298,14 @@
     },
     {
       "name": "FRONTEND_ROUTE",
-      "description": "The exposed hostname that will route to the Dancer service",
+      "description": "The exposed hostname that will route Dancer frontend service",
       "value": "dancer.app"
     },
     {
-      "name": "GITHUB_WEBHOOK_SECRET",
-      "description": "A secret string used to configure the GitHub webhook",
+      "name": "SECRET_KEY_BASE",
+      "description": "Your secret key for verifying the integrity of signed cookies",
       "generate": "expression",
-      "from": "[a-zA-Z0-9]{40}"
+      "from": "[a-z0-9]{127}"
     },
     {
       "name": "ADMIN_USERNAME",
@@ -322,13 +334,7 @@
     {
       "name": "MYSQL_DATABASE",
       "description": "database name",
-      "value": "root"
-    },
-    {
-      "name": "SECRET_KEY_BASE",
-      "description": "Your secret key for verifying the integrity of signed cookies",
-      "generate": "expression",
-      "from": "[a-z0-9]{127}"
+      "value": "sampledb"
     }
   ]
 }
diff --git a/openshift/templates/dancer.json b/openshift/templates/dancer.json
index f8baa38..111c0f2 100644
--- a/openshift/templates/dancer.json
+++ b/openshift/templates/dancer.json
@@ -50,16 +50,29 @@
       }
     },
     {
-      "kind": "ImageStream",
+      "kind": "ImageStreamTag",
       "apiVersion": "v1",
       "metadata": {
-        "name": "dancer-example",
+        "name": "dancer-example:latest",
         "annotations": {
           "description": "Keeps track of changes in the application image"
         }
       }
     },
     {
+      "kind": "ImageStreamTag",
+      "apiVersion": "v1",
+      "metadata": {
+        "name": "perl:5.16",
+        "annotations": {
+          "description": "Keeps track of changes in the Perl base image"
+        }
+      },
+      "spec": {
+        "dockerImageRepository": "openshift/perl-516-centos7"
+      }
+    },
+    {
       "kind": "BuildConfig",
       "apiVersion": "v1",
       "metadata": {
@@ -81,15 +94,14 @@
           "sourceStrategy": {
             "from": {
               "kind": "ImageStreamTag",
-              "namespace": "openshift",
               "name": "perl:5.16"
             }
           }
         },
         "output": {
           "to": {
-            "kind": "ImageStreamTag",
-            "name": "dancer-example:latest"
+            "kind": "ImageStream",
+            "name": "dancer-example"
           }
         },
         "triggers": [
@@ -99,7 +111,7 @@
           {
             "type": "GitHub",
             "github": {
-              "secret": "${GITHUB_WEBHOOK_SECRET}"
+              "secret": "secret123"
             }
           }
         ]
@@ -176,16 +188,10 @@
     },
     {
       "name": "FRONTEND_ROUTE",
-      "description": "The exposed hostname that will route to the Dancer service",
+      "description": "The exposed hostname that will route Dancer frontend service",
       "value": "dancer.app"
     },
     {
-      "name": "GITHUB_WEBHOOK_SECRET",
-      "description": "A secret string used to configure the GitHub webhook",
-      "generate": "expression",
-      "from": "[a-zA-Z0-9]{40}"
-    },
-    {
       "name": "SECRET_KEY_BASE",
       "description": "Your secret key for verifying the integrity of signed cookies",
       "generate": "expression",
```

**Comment by rhcarvalho** [comment]
Sorry for the brevity, I did the diff and am writing from my phone.
The - lines are my branch (A), the + lines are yours (B). Summarizing:
- A creates a IS for the build output, B creates a IST. Not sure we need a IST here. @bparees, could you comment?
- B creates a IST for perl, we should not add this.
- A has param to specify GitHub Webhook

@ewolinetz, sorry my intention was not to repeat your work.

**Comment by ewolinetz** [comment]
@rhcarvalho its nbd, just didn't want us to lose anything.  I had cleaned up some old configurations in addition to matching template design.  FYI B also uses an IST for the mysql container.

**Comment by bparees** [comment]
1) @rhcarvalho @ewolinetz we should be creating an IST for output.
2) Agree, should not create an IST for perl ( @ewolinetz sorry you weren't part of that discussion)
3) Param for github is correct.

i'm going to merge this one and then @ewolinetz you can rebase and update your PR to make the build output change.

**Pull request merged**
