### PR TITLE
fix yaml dependency

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mnagy fyi this repo totally bit-rotted for some reason.  w/o these changes the app won't start at all due to missing dependencies (shows up in /tmp/error_log)

**Comment by mnagy** [comment]
Hmm, maybe needs some extended tests?

**Comment by mfojtik** [comment]
we should already have this covered by examples test @bparees wrote

**Comment by bparees** [comment]
@mfojtik we do.  just that no one runs them.

**Comment by mfojtik** [comment]
@bparees we should run them daily and send reports to devex folks for beginning maybe :)

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/origin_extended/

On Tue, Nov 3, 2015 at 10:22 AM, Michal Fojtik notifications@github.com
wrote:

> @bparees https://github.com/bparees we should run them daily and send
> reports to devex folks for beginning maybe :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openshift/dancer-ex/pull/25#issuecomment-153386831.

## 

Ben Parees | OpenShift

**Pull request merged**
